base_url = "https://astrid-klipfel.fr"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
navbar=[
    {url = "presentation.md"},
    {url = "publications/_index.md"},
    {url = "talks/_index.md"},
    {url = "teaching.md"},
    {url = "resume/resume_astrid_klipfel.pdf", title = "Resume"}
]
