base_url = "https://research.astrid-klipfel.net"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
navbar=[
    {url = "presentation.md"},
    {url = "publications/_index.md"},
    {url = "talks/_index.md"},
    {url = "teaching.md"},
    {url = "resume/resume_astrid_klipfel.pdf", title = "Resume"}
]
[extra.author]
name = "Astrid Klipfel"
description = "Machine Learning applied to Materials Science and Neuro-symbolic AI"
location = "Czech Technical University in Prague"
email = "astridklipfel@gmail.com"
github = "https://github.com/aklipf"
scholar = "https://scholar.google.com/citations?hl=en&user=-gNXRYQAAAAJ"
orcid = "https://orcid.org/0009-0004-8310-4573"
