[author]
name = "Astrid Klipfel"
description = "Machine Learning applied to Materials Science"
location = "Université d'Artois"
email = "klipfel@cril.fr"
github = "https://github.com/aklipf"
scholar = "https://scholar.google.com/citations?hl=en&user=-gNXRYQAAAAJ"
orcid = "https://orcid.org/0009-0004-8310-4573"